repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-ast
    -   id: trailing-whitespace
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        args: [--line-length, "100"]

# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v1.2.3
#     hooks:
#     -   id: flake8
